version: '3.8'
services:
  restaurantdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID : "Developer"
    volumes:
      - D:\docker_volumes\sql_data:/var/opt/mssql/data
    ports:
      - "1433:1433"
